config/routes.rb
Rails.application.routes.draw do

  resources :stamps do
    collection { get :search }
  end

  get '/stamps/:id/set' => 'stamps#set', as: 'set'

  root 'stamps#index'

  #api
  namespace :api do
    namespace :v1 do
      #resources :stamps, only: [:index, :show]
      resources :stamps do
        collection { get :search }
      end
    end
  end
  get '/api/v1/stamps/:id/set' => 'api/v1/stamps#set', as: 'set_api'


end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
=begin
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  #Stamp.__elasticsearch__.client = Elasticsearch::Client.new #host: '192.168.99.100', log: true

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: ['computed_description^10', 'country_name', 'sg_number^5']
                }
            },
            highlight: {
                pre_tags: ['<em class="label label-highlight">'],
                post_tags: ['</em>'],
                fields: {
                    title:   { number_of_fragments: 0 },
                    content: { fragment_size: 25 }
                }
            }
        }
    )
  end


end

Stamp.import force:true # for auto sync model with elastic search
=end

end

app/controllers/api/v1/stamps_controller.rb
class Api::V1::StampsController < Api::V1::BaseController
  include StampsHelper

  def show
    stamp = Stamp.find(params[:id])
    render(json: Api::V1::StampSerializer.new(stamp).to_json)
  end


  def index
    stamps = Stamp.all

    render(
        json: ActiveModel::ArraySerializer.new(
            stamps,
            each_serializer: Api::V1::StampSerializer,
            root: 'stamps',
        )
    )
  end


  def search
    stamps = Stamp.search(params[:q]).records
    render(
        json: ActiveModel::ArraySerializer.new(
            stamps,
            each_serializer: Api::V1::StampSerializer,
            root: 'stamps',
        )
    )
  end


  def set
    puts "entering set".colorize(:red)
    stamp = Stamp.find(params[:id])
    stamps = find_stamps_in_set_with(stamp)
    render(
        json: ActiveModel::ArraySerializer.new(
            stamps,
            each_serializer: Api::V1::StampSerializer,
            root: 'stamps',
        )
    )
  end


end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  include StampsHelper


  before_action :set_stamp, only: [:show, :edit, :update, :destroy]


  def index
    @count=0
    if params[:issuer]
        @stamps = Stamp.where('issuer=?', params[:issuer]).order('id').page(params[:page])
        @count = Stamp.where('issuer=?', params[:issuer]).count
    else
      @stamps = Stamp.where('issuer=?','XYZ').page(params[:page])
    end

  end


  def search
    @stamps = Stamp.search(params[:q]).page(params[:page]).records
    render action: "index"
  end


  def new
    @stamp = Stamp.new
  end


  def create
    @stamp = Stamp.new(stamp_params)

    respond_to do |format|
      if @stamp.save!
        format.html {
          flash[:success] = "Stamp was successfully created."
          redirect_to stamps_path
        }
        format.json { render :show, status: :created, location: @stamp }
      else
        format.html { render :new }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end

  end


  def edit
  end


  def update
    @stamp = Stamp.find(params[:id])
    @stamp.update_attributes(stamp_params)

    respond_to do |format|
      if @stamp.save!
        format.html {
          flash[:success] = "Stamp was successfully updated."
          redirect_to stamps_path
        }
        format.json { render :show, status: :created, location: @stamp }
      else
        format.html { render :new }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @stamp = Stamp.find(params[:id])
    @stamp.destroy
    redirect_to stamps_path
  end


  def set
    @stamp = Stamp.find(params[:id])
    @set = find_stamps_in_set_with(@stamp)
  end


  def stamp_params
    params.require(:stamp).permit(:country_name,
                                  :sub_country_name,
                                  :set_description,
                                  :set_text,
                                  :set_designer,
                                  :set_start_year,
                                  :set_start_month,
                                  :set_start_day,
                                  :set_end_year,
                                  :set_end_month,
                                  :set_end_day,
                                  :set_perf_info,
                                  :set_type_number,
                                  :set_watermark_number,
                                  :sg_number,
                                  :stamp_prefix,
                                  :stamp_sg_number,
                                  :stamp_pre_suffix,
                                  :stamp_suffix,
                                  :stamp_description,
                                  :variety_description,
                                  :stamp_issue_price,
                                  :stamp_type_number,
                                  :stamp_unused,
                                  :stamp_used,
                                  :variety_flag)
  end


  private


  # Use callbacks to share common setup or constraints between actions.
  def set_stamp
    @stamp = Stamp.find(params[:id])
  end


end

app/helpers/stamps_helper.rb
module StampsHelper


  def find_stamps_in_set_with(stamp)
    sql = "select * from stamps where issuer = '" + stamp.issuer + "' and "

    if stamp.set_description.nil?
      sql += "set_description is null and "
    else
      sql += "set_description = '" + stamp.set_description + "' and "
    end

    if stamp.set_text.nil?
      sql += "set_text is null and "
    else
      sql += "set_text = '" + stamp.set_text + "' and "
    end

    if stamp.set_designer.nil?
      sql += "set_designer is null and "
    else
      sql += "set_designer = '" + stamp.set_designer + "' and "
    end

=begin
    if stamp.set_start_year.nil?
      sql += "set_start_year is null and "
    else
      sql += "set_start_year = '" + stamp.set_start_year + "' and "
    end

    if stamp.set_start_month.nil?
      sql += "set_start_month is null and "
    else
      sql += "set_start_month = '" + stamp.set_start_month + "' and "
    end

    if stamp.set_start_day.nil?
      sql += "set_start_day is null and "
    else
      sql += "set_start_day = '" + stamp.set_start_day + "' and "
    end

    if stamp.set_end_year.nil?
      sql += "set_end_year is null and "
    else
      sql += "set_end_year = '" + stamp.set_end_year + "' and "
    end

    if stamp.set_end_month.nil?
      sql += "set_end_month is null and "
    else
      sql += "set_end_month = '" + stamp.set_end_month + "' and "
    end

    if stamp.set_end_day.nil?
      sql += "set_end_day is null and "
    else
      sql += "set_end_day = '" + stamp.set_end_day + "' and "
    end
=end

    if stamp.set_perf_info.nil?
      sql += "set_perf_info is null and "
    else
      sql += "set_perf_info = '" + stamp.set_perf_info + "' and "
    end

    if stamp.set_type_number.nil?
      sql += "set_type_number is null and "
    else
      sql += "set_type_number = '" + stamp.set_type_number + "' and "
    end

    if stamp.set_watermark_number.nil?
      sql += "set_watermark_number is null  "
    else
      sql += "set_watermark_number = '" + stamp.set_watermark_number + "'  "
    end

    sql += " order by issuer, id"
    set = Stamp.find_by_sql(sql)


    return set
  end


end

app/views/stamps/_form.html.erb
<%= form_for @stamp do |f| %>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:country_name].blank? %>">
      <%= f.label :country_name %>
      <%= f.text_field :country_name, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:sub_country_name].blank? %>">
      <%= f.label :sub_country_name %>
      <%= f.text_field :sub_country_name, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_description].blank? %>">
      <%= f.label :set_description %>
      <%= f.text_field :set_description, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_text].blank? %>">
      <%= f.label :set_text %>
      <%= f.text_area :set_text, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_designer].blank? %>">
      <%= f.label :set_designer %>
      <%= f.text_field :set_designer, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_start_year].blank? %>">
      <%= f.label :set_start_year %>
      <%= f.text_field :set_start_year, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_start_month].blank? %>">
      <%= f.label :set_start_month %>
      <%= f.text_field :set_start_month, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_start_day].blank? %>">
      <%= f.label :set_start_day %>
      <%= f.text_field :set_start_day, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_end_year].blank? %>">
      <%= f.label :set_end_year %>
      <%= f.text_field :set_end_year, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_end_month].blank? %>">
      <%= f.label :set_end_month %>
      <%= f.text_field :set_end_month, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_end_day].blank? %>">
      <%= f.label :set_end_day %>
      <%= f.text_field :set_end_day, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_perf_info].blank? %>">
      <%= f.label :set_perf_info %>
      <%= f.text_field :set_perf_info, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_type_number].blank? %>">
      <%= f.label :set_type_number %>
      <%= f.text_field :set_type_number, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:set_watermark_number].blank? %>">
      <%= f.label :set_watermark_number %>
      <%= f.text_field :set_watermark_number, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:sg_number].blank? %>">
      <%= f.label :sg_number %>
      <%= f.text_field :sg_number, class: 'form-control border-input', autofocus: true, readonly: 'readonly' %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_prefix].blank? %>">
      <%= f.label :stamp_prefix %>
      <%= f.text_field :stamp_prefix, class: 'form-control border-input', autofocus: true %>
    </div>



    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_prefix].blank? %>">
      <%= f.label :stamp_prefix %>
      <%= f.text_field :stamp_prefix, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_sg_number].blank? %>">
      <%= f.label :stamp_sg_number %>
      <%= f.text_field :stamp_sg_number, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_pre_suffix].blank? %>">
      <%= f.label :stamp_pre_suffix %>
      <%= f.text_field :stamp_pre_suffix, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_suffix].blank? %>">
      <%= f.label :stamp_suffix %>
      <%= f.text_field :stamp_suffix, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_description].blank? %>">
      <%= f.label :stamp_description %>
      <%= f.text_field :stamp_description, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:variety_description].blank? %>">
      <%= f.label :variety_description %>
      <%= f.text_field :variety_description, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_issue_price].blank? %>">
      <%= f.label :stamp_issue_price %>
      <%= f.text_field :stamp_issue_price, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_type_number].blank? %>">
      <%= f.label :stamp_type_number %>
      <%= f.text_field :stamp_type_number, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_unused].blank? %>">
      <%= f.label :stamp_unused %>
      <%= f.text_field :stamp_unused, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:stamp_used].blank? %>">
      <%= f.label :stamp_used %>
      <%= f.text_field :stamp_used, class: 'form-control border-input', autofocus: true %>
    </div>

    <div class="form-group <%= "has-error".html_safe unless @stamp.errors[:variety_flag].blank? %>">
      <%= f.label :variety_flag %>
      <%= f.text_field :variety_flag, class: 'form-control border-input', autofocus: true %>
    </div>



    <%= f.submit "Save", class: "btn btn-success btn-fill btn-block" %>
    <%= link_to "Delete", @stamp, method: :delete, class: 'btn btn-block btn-fill btn-danger' %>

    <p>&nbsp;</p>
    <p>&nbsp;</p>

<% end %>

app/views/stamps/edit.html.erb
<h1>Stamps#edit</h1>
<p>Find me in app/views/stamps/edit.html.erb</p>

app/views/stamps/index.html.erb
<h3 class="title">My Catalogs</h3>
<%= link_to "France", "/stamps?issuer=France", class: "btn btn-large btn-primary" %>
<%= link_to "France > Alexandretta", "/stamps?issuer=France > Alexandretta", class: "btn btn-large btn-primary" %>
<%= link_to "GB Concise", "/stamps?country_name=Great Britain", class: "btn btn-large btn-primary" %>
<hr>

<%= form_tag search_stamps_path, method: 'get' do %>
    <div class="input-group">
      <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>

      <span class="input-group-btn">
            <button type="button" class="btn btn-default">
              <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>

<% end %>

<hr>

<% if @stamps.count > 0 %>

    <h3><%= @count %> stamps found.</h3>

    <%= paginate @stamps %>
    <ul class="users">
    <% @stamps.each do |stamp| %>

          <li>
            <%= link_to image_tag(stamp.local_image_url, alt: stamp.image_url, height: 64) %>
            <%= link_to stamp.issuer + ' SG ' + stamp.sg_number, set_path(stamp) %>
            <%= stamp.computed_description %>
          </li>

    <% end %>
    </ul>

    <div class="text-center">
      <%= paginate @stamps %>
    </div>

<% end %>

<hr>

<p style="text-align: center; margin-bottom: 21px">
  <%= link_to 'New Stamp', new_stamp_path, class: 'btn btn-primary', style: 'color: #fff' %>
</p>

</div>

app/views/stamps/new.html.erb
<div class="wrapper">
  <div class="main">
    <div class="section">
      <div class="container">
        <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 ">
          <h3 class="title-uppercase">New Stamp</h3>
          <p>&nbsp;</p>
          <%= render 'form' %>
          <p>&nbsp;</p>
          <%= link_to 'Back to list', stamps_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stamps/set.html.erb
<div class="wrapper">
  <div class="main">
    <div class="section">
      <div class="container">
        <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 ">
          <h3 class="title-uppercase"><%= @stamp.issuer %> SG <%= @stamp.sg_number %></h3>

          <p><center><%= image_tag @stamp.local_image_url %></center></p>
          <p><%= @stamp.set_designer %></p>
          <p><b><%= @stamp.set_start_year %></b> (<%= @stamp.set_start_day %> <%= @stamp.set_start_month %>)-<b><%= @stamp.set_end_year %></b> <%= @stamp.set_description %></p>
          <table border="1">
            <% @previous_stamp = Stamp.new %>
            <% @set.each do |stamp| %>
                <% if stamp.set_text != @previous_stamp.set_text && !@previous_stamp.sg_number.nil? %>
                    <tr><td colspan="5"><%= @previous_stamp.set_text %></td></tr>
                <% else %>
                    <tr <%= "bgcolor='yellow'".html_safe if stamp.sg_number == @stamp.sg_number %>&nbsp;&nbsp;>
                      <td><%= stamp.sg_number %>&nbsp;&nbsp;</td>
                      <td><%= stamp.stamp_issue_price %>&nbsp;&nbsp;</td>
                      <td><%= stamp.stamp_description %>&nbsp;&nbsp;</td>
                      <td><%= stamp.stamp_unused %>&nbsp;&nbsp;</td>
                      <td><%= stamp.stamp_used %>&nbsp;&nbsp;</td>
                    </tr>
                <% end %>
                <% @previous_stamp = stamp %>
            <% end %>
            <tr><td colspan="5"><%= @previous_stamp.set_text %></td></tr>
          </table>
          <p>&nbsp;</p>
          <%= link_to 'Back to list', stamps_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stamps/show.html.erb
<%= image_tag(stamp.local_image_url) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table>
      <% @stamp.attribute_names.each do |f| %>
          <tr>
            <td><label><%= f %>:</label></td>
            <td><%= @stamp[f] %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>